### PR TITLE
Update to PulseAudio 12.2

### PR DESCRIPTION
**Pull request by archfan**

### CODE REVIEW

**Comment by oxij** [comment]
Ah, I guess, thanks for taking time to make a PKGBUILD for this. :)

I think the headers shouldn't contain any C files. `3rdparty/pulseaudio-headers/pulse` should coincide with `/usr/include/pulse` of the original PA package. You may leave it as is and I'll then update the headers myself. It is, indeed, a bit painful to do ATM.

As to the Makefile changes:

```diff
-PREFIX?=/usr/local
+PREFIX?=/usr
```

why? Can't you specify it in the PKGBUILD itself? I'm not against this, but I expected people on hier(7)-conformant distros to install it into `/usr/local` by default for testing.

```diff
 lib%.pc: %.pc.in
-       @sed "s%@PREFIX@%$(PREFIX)%g" $< > $@
+       @sed "s%@PREFIX@%$(DESTDIR)$(PREFIX)%g" $< > $@
 
 cmakes: PulseAudioConfig.cmake PulseAudioConfigVersion.cmake
 
 %.cmake: %.cmake.in
-       @sed "s%@PREFIX@%$(PREFIX)%g" $< > $@
+       @sed "s%@PREFIX@%$(DESTDIR)$(PREFIX)%g" $< > $@
```

are you sure? IIRC DESTDIR is a temporary directory, I would think that you won't want to have it mentioned in `pc` and `cmake` files.

I think `DESTDIR` also needs to be declared in the `Makefile` with something like

```diff
+DESTDIR?=
 PREFIX?=/usr/local
```

The rest looks good to me.

Also, why "anti-communism" tag on the repo?

**Comment by archfan** [comment]
Thanks for your feedback. I'll remove the C files from the headers and change the PREFIX back to /usr/local. I can alternatively just use sed to instruct pacman to do the right thing.

Also good call with DESTDIR

The PKGBUILD is here: https://github.com/archfan/PKGBUILD/blob/master/libcardiacarrest/PKGBUILD
Lib32: https://github.com/archfan/PKGBUILD/blob/master/lib32-libcardiacarrest/PKGBUILD

**Comment by archfan** [comment]
Seems to work alright so far :+1: 

> Also, why "anti-communism" tag on the repo?

Communism in the form of liberalism and multiculturalism is once again spreading in Europe. The death toll is rising quickly.

**Comment by oxij** [comment]
Thanks. I'll pick/edit/test these changes later this week.

Updating of PA headers and versioning copy-paste clearly needs to be automated anyway.

**Comment by archfan** [comment]
Should be fairly trivial to implement :100:

**Comment by oxij** [comment]
I made d705c0efe891147773a436100f7e5e14f38e6348 based on your changes, rebuilt the world, tested it for a while, and it seems to work as expected. I'll reset master to that revision in another week or so if all is still well then.

Concerning https://github.com/archfan/PKGBUILD/blob/master/libcardiacarrest/PKGBUILD, it LGTM, but the version should be "$PA_VERSION.$CA_VERSION", d705c0efe891147773a436100f7e5e14f38e6348 now has `version.mk` to make versioning stuff cleaner. Also, I don't see `glib` in dependencies there, which looks strange.

If that looks good to you, then, I think, this can be closed.

**Comment by oxij** [comment]
This is now a part of https://github.com/oxij/libcardiacarrest/releases/tag/v12.2.8 release.

**Pull request closed without merging**
